FROM node:18

WORKDIR /app

ARG NUXT_GOOGLE_CLIENT_ID
ARG NUXT_PUBLIC_APPLE_CLIENT_ID

ENV NUXT_GOOGLE_CLIENT_ID=$NUXT_GOOGLE_CLIENT_ID
ENV NUXT_PUBLIC_APPLE_CLIENT_ID=$NUXT_PUBLIC_APPLE_CLIENT_ID

COPY . .

RUN npm install

RUN npm run build

EXPOSE 3000

CMD ["node", ".output/server/index.mjs"]
